/**
 * Represents raw or processed video metadata extracted from a video source.
 */
export interface VideoData {
  /** The hosting service ("youtube" or "instagram"). */
  platform: "youtube" | "instagram";
  /** Unique id parsed or fetched for the specific video. */
  video_id: string;
  /** Full URL path of the video. */
  source_url: string;
  /** The creator username or identifier. */
  creator: string;
  /** Custom creator user display name if available, otherwise null. */
  creator_name: string | null;
  /** Accumulated view count. */
  views: number;
  /** Accumulated like count. */
  likes: number;
  /** Accumulated comment count. */
  comments: number;
  /** Computed engagement score (e.g. ((likes + comments) / views) * 100). */
  engagement_rate: number;
  /** Array of associated hashtags. */
  hashtags: string[];
  /** Video description or caption text. */
  caption?: string;
  /** Ingested raw video transcript text. */
  transcript?: string;
  /** How the transcript was retrieved ("native", "whisper", or null). */
  transcript_source?: string;
  /** Video duration in seconds. */
  duration?: number;
}

/**
 * The standard response object returned by the ingestion service.
 */
export interface IngestResponse {
  /** Success status code string. */
  status: "success" | "error";
  /** Data model containing the YouTube video analysis. */
  video_a: VideoData;
  /** Data model containing the Instagram video analysis. */
  video_b: VideoData;
}

/**
 * Citation entry referencing a source location used to formulate a RAG answer.
 */
export interface Citation {
  /** The origin source node type. */
  source: "transcript" | "metadata";
  /** The database document video ID. */
  video_id?: string;
  /** Specific chunk index inside transcript lists. */
  chunk_index?: number;
  /** Custom video target identifier labels. */
  video?: string;
}

/**
 * Direct response payload returned by non-streaming chat requests.
 */
export interface ChatResponse {
  /** Answer generated by the LLM. */
  answer: string;
  /** Citation reference entries used in LLM generation. */
  citations: Citation[];
}

/**
 * Visual chat message structure rendered in the AI Chat window.
 */
export interface Message {
  /** Unique UUID representing the message bubble. */
  id: string;
  /** The speaker role. */
  role: "user" | "assistant";
  /** Content text inside the message bubble. */
  content: string;
  /** Citations associated with the response. */
  citations?: Citation[];
  /** Flag showing if token streaming is actively running. */
  isStreaming?: boolean;
}

