import json
import logging
from typing import Dict, Any, Generator
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from app.rag.graph import app as langgraph_app, stream_app
from app.rag.nodes.generator_node import model
from app.rag.memory_store import session_memory
from app.rag.citation_evaluator import filter_citations

logger = logging.getLogger(__name__)

router = APIRouter()


class ChatRequest(BaseModel):
    session_id: str
    question: str


@router.post("/api/chat")
def chat(request: ChatRequest) -> Dict[str, Any]:
    """
    Standard HTTP POST endpoint that executes the entire LangGraph RAG pipeline,
    generating a single response with relevant citations.
    
    Args:
        request: ChatRequest body containing session_id and query.
        
    Returns:
        A dictionary containing the generated 'answer' and list of 'citations'.
    """
    logger.info("Received standard chat request for session: %s", request.session_id)
    
    initial_state = {
        "session_id": request.session_id,
        "question": request.question,
        "history": session_memory.get(request.session_id, []),
        "retrieved_chunks": [],
        "citations": [],
        "answer": ""
    }
    
    try:
        result = langgraph_app.invoke(initial_state)
        logger.info("Successfully executed full RAG graph invocation for session: %s", request.session_id)
        return {
            "answer": result.get("answer", ""),
            "citations": result.get("citations", [])
        }
    except Exception as e:
        logger.exception("Failed to execute full RAG graph invocation.")
        raise HTTPException(status_code=500, detail=f"RAG execution failed: {str(e)}")


@router.post("/api/chat/stream")
def stream_chat(request: ChatRequest) -> StreamingResponse:
    """
    Streaming HTTP POST endpoint that runs the LangGraph RAG pipeline up to prompt creation,
    then streams token chunks generated by the Gemini model to the client.
    
    Args:
        request: ChatRequest body containing session_id and query.
        
    Returns:
        A StreamingResponse yielding JSON lines of tokens and final citations.
    """
    logger.info("Received streaming chat request for session: %s", request.session_id)
    
    initial_state = {
        "session_id": request.session_id,
        "question": request.question,
        "history": session_memory.get(request.session_id, []),
        "retrieved_chunks": [],
        "citations": [],
        "answer": ""
    }
    
    try:
        # Run graph up to prompt node to extract prompts and context
        result = stream_app.invoke(initial_state)
        prompt = result.get("prompt", "")
    except Exception as e:
        logger.exception("Failed to execute streaming RAG graph preparation.")
        raise HTTPException(status_code=500, detail=f"RAG streaming preparation failed: {str(e)}")
        
    if not prompt:
        logger.error("Generated prompt is empty. Aborting streaming generation.")
        raise HTTPException(status_code=500, detail="Failed to construct a valid prompt for generation.")
    
    def generate() -> Generator[str, None, None]:
        if model is None:
            logger.error("Gemini model is uninitialized. Streaming fallback error token.")
            err_answer = "I cannot determine this from the available video data due to model configuration issues."
            yield json.dumps({"type": "token", "content": err_answer}) + "\n"
            yield json.dumps({"type": "citations", "citations": []}) + "\n"
            return

        full_answer = ""
        try:
            logger.info("Starting Gemini content stream generation...")
            response = model.generate_content(prompt, stream=True)
            for chunk in response:
                if chunk.text:
                    full_answer += chunk.text
                    yield json.dumps({"type": "token", "content": chunk.text}) + "\n"
            logger.info("Gemini content stream successfully completed.")
        except ValueError as ve:
            logger.warning("Gemini model generated empty or block-filtered response: %s", ve)
            full_answer = "I cannot determine this from the available video data. The model was unable to generate a valid response."
            yield json.dumps({"type": "token", "content": full_answer}) + "\n"
        except Exception as e:
            logger.exception("Error occurred during Gemini content stream generation.")
            full_answer = f"An error occurred while generating the response: {str(e)}"
            yield json.dumps({"type": "token", "content": full_answer}) + "\n"
                
        # Evaluate and filter citations based on what was actually mentioned in full_answer
        all_citations = result.get("citations", [])
        filtered_citations = []
        if all_citations:
            try:
                logger.info("Evaluating citations against generated response...")
                filtered_citations = filter_citations(request.question, full_answer, all_citations)
            except Exception as ce:
                logger.exception("Failed to filter citations. Falling back to all retrieved citations.")
                filtered_citations = all_citations
            
        yield json.dumps({"type": "citations", "citations": filtered_citations}) + "\n"
                
        # Update session memory after stream completes
        session_id = request.session_id
        try:
            history = session_memory.get(session_id, [])
            if not isinstance(history, list):
                history = []
            history.append({
                "role": "user",
                "content": request.question
            })
            history.append({
                "role": "assistant",
                "content": full_answer
            })
            session_memory[session_id] = history
            logger.info("Updated session memory for session: %s", session_id)
        except Exception as he:
            logger.error("Failed to update session memory in stream: %s", he)

    return StreamingResponse(generate(), media_type="application/x-ndjson")

